### ISSUE TITLE
Android.App.Result Always Returns Canceled

### ISSUE THREAD

**Issue by Light1c3** [googlesamples/android-fit-xamarin#1]
I'm attempting the run the sample project as is, but keep getting an error on `if (resultCode == Android.App.Result.Ok)` as it keeps returning a result of Android.App.Result.Canceled

Any recommendation?

**Comment by AgustinBonilla** [comment]
I am having the same problem now, does anyone know how to solve this?

**Comment by AgustinBonilla** [comment]
It is necessary to configure authentication with google api: https://developers.google.com/fit/android/get-api-key

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
